# Site settings
title: Kaan Satir
# email:
description: "Exercise, Nutrition, Financial Markets, Coding, Prompting"
# baseurl: "//hos.github.io"
# url: "//hos.github.io"
url: "https://kaansatir.github.io/"
# twitter_username:
github_username:  kaansatir

# Build settings
markdown: kramdown
permalink: pretty
paginate: 6
paginate_path: "/:num/"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from


# configure kramdown
kramdown:
  parse_block_html: true
